import PptxGenJS from "pptxgenjs";

// Parse **bold** markdown text into pptx text fragments
function parseBoldText(text) {
  const parts = text.split(/(\*\*[^*]+\*\*)/g);
  return parts.map((part) => {
    if (part.startsWith("**") && part.endsWith("**")) {
      return { text: part.slice(2, -2), options: { bold: true } };
    }
    return { text: part, options: {} };
  }).filter(p => p.text); // Remove empty parts
}

// Clean ALL markdown symbols from text
function cleanText(text) {
  return text
    .replace(/^#{1,6}\s*/g, "")      // Remove ### headers
    .replace(/\*{3,}/g, "")           // Remove ***
    .replace(/\*{2}/g, "")            // Remove **
    .replace(/^\*+\s*/g, "")          // Remove leading * 
    .replace(/\*+$/g, "")             // Remove trailing *
    .replace(/^[-•]\s*/g, "")         // Remove bullet markers
    .replace(/<[^>]*>/g, "")          // Remove HTML tags
    .replace(/#+/g, "")               // Remove any remaining #
    .trim();
}

// Color themes
const themes = {
  purple: { primary: "667eea", secondary: "764ba2", accent: "10b981", dark: "1e293b", light: "f8fafc", text: "334155" },
  blue: { primary: "0ea5e9", secondary: "3b82f6", accent: "60a5fa", dark: "1e293b", light: "f0f9ff", text: "334155" },
  green: { primary: "10b981", secondary: "059669", accent: "34d399", dark: "1e293b", light: "ecfdf5", text: "334155" },
  orange: { primary: "f97316", secondary: "fb923c", accent: "f59e0b", dark: "1e293b", light: "fff7ed", text: "334155" },
};

export async function buildPptxFromJson(structure, themeName = "purple") {
  const pptx = new PptxGenJS();
  const theme = themes[themeName] || themes.purple;

  pptx.layout = "LAYOUT_WIDE";
  pptx.author = "AI PPT Generator";
  pptx.company = "AI PPT Chat";
  pptx.subject = structure.title || "AI Presentation";

  // ----- TITLE SLIDE -----
  if (structure.title) {
    const slide = pptx.addSlide();
    slide.background = { fill: theme.primary };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 1.5,
      fill: { color: theme.secondary },
    });

    // Clean title from all markdown
    const cleanTitle = cleanText(structure.title);

    slide.addText(cleanTitle, {
      x: 0.5,
      y: 2.5,
      w: 9,
      h: 2,
      fontSize: 48,
      bold: true,
      color: "FFFFFF",
      align: "center",
      valign: "middle",
      shrinkText: true,
      wrap: true,
      lineSpacing: 24,
    });

    if (structure.subtitle) {
      slide.addText(cleanText(structure.subtitle), {
        x: 1,
        y: 4.4,
        w: 8,
        h: 0.8,
        fontSize: 24,
        color: "FFFFFF",
        align: "center",
        transparency: 20,
        wrap: true,
        shrinkText: true,
      });
    }

    const date = new Date().toLocaleDateString("en-US", {
      year: "numeric",
      month: "long",
      day: "numeric",
    });
    slide.addText(`Generated by AI | ${date}`, {
      x: 0.5,
      y: 6.8,
      w: 9,
      h: 0.3,
      fontSize: 11,
      color: "FFFFFF",
      align: "center",
    });
  }

  // ----- CONTENT SLIDES -----
  (structure.slides || []).forEach((sl, idx) => {
    const slide = pptx.addSlide();
    slide.background = { color: theme.light };

    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0,
      w: "100%",
      h: 0.25,
      fill: { color: theme.primary },
    });
    slide.addShape(pptx.ShapeType.rect, {
      x: 0,
      y: 0.25,
      w: 0.1,
      h: 7.25,
      fill: { color: theme.accent },
    });

    slide.addText(`${idx + 1}`.padStart(2, "0"), {
      x: 9,
      y: 0.4,
      w: 0.6,
      h: 0.4,
      fontSize: 16,
      color: "FFFFFF",
      bold: true,
      align: "center",
      valign: "middle",
    });

    // Clean title from all markdown symbols
    if (sl.title) {
      const cleanSlideTitle = cleanText(sl.title);
      
      slide.addText(cleanSlideTitle, {
        x: 0.6,
        y: 0.8,
        w: 8,
        h: 1,
        fontSize: 32,
        bold: true,
        color: theme.dark,
        wrap: true,
        shrinkText: true,
        lineSpacing: 26,
      });
      slide.addShape(pptx.ShapeType.rect, {
        x: 0.6,
        y: 1.75,
        w: 2.5,
        h: 0.06,
        fill: { color: theme.accent },
      });
    }

    // Bullets - cleaned from all symbols
    let currentY = 2.2;
    const maxHeight = 6.5;
    const lineHeight = 0.9;

    (sl.bullets || []).forEach((b, i) => {
      if (currentY > maxHeight) return; // stop if too full

      // Clean bullet text from all markdown
      const cleanBullet = cleanText(b);
      
      if (!cleanBullet) return; // Skip empty bullets

      const bulletHeight = lineHeight;
      const fontSize =
        cleanBullet.length > 180 ? 14 : cleanBullet.length > 120 ? 16 : cleanBullet.length > 80 ? 18 : 20;

      // Bullet dot
      slide.addShape(pptx.ShapeType.ellipse, {
        x: 0.7,
        y: currentY + 0.15,
        w: 0.15,
        h: 0.15,
        fill: { color: theme.accent },
      });

      // Bullet text - completely clean
      slide.addText(cleanBullet, {
        x: 1.1,
        y: currentY,
        w: 7.8,
        h: bulletHeight,
        fontSize,
        color: theme.text,
        wrap: true,
        shrinkText: true,
        valign: "top",
        lineSpacing: 22,
      });

      currentY += lineHeight + 0.4; // spacing between bullets
    });

    // Footer
    slide.addShape(pptx.ShapeType.rect, {
      x: 0.5,
      y: 6.95,
      w: 9,
      h: 0.02,
      fill: { color: theme.primary },
    });
    slide.addText(`${idx + 1} / ${structure.slides.length}`, {
      x: 8.5,
      y: 7.05,
      w: 1,
      h: 0.2,
      fontSize: 10,
      color: theme.dark,
      align: "right",
    });

    // Optional image
    if (sl.imageBase64 || sl.imageUrl) {
      try {
        slide.addImage({
          data: sl.imageBase64 || sl.imageUrl,
          x: 7.2,
          y: 2.4,
          w: 2.2,
          h: 2.2,
          sizing: { type: "contain", w: 2.2, h: 2.2 },
        });
      } catch (e) {
        console.warn("Image error:", e);
      }
    }
  });

  // ----- THANK YOU SLIDE -----
  if (structure.slides.length > 2) {
    const slide = pptx.addSlide();
    slide.background = { fill: theme.primary };
    slide.addText("Thank You", {
      x: 1,
      y: 2.5,
      w: 8,
      h: 1.2,
      fontSize: 54,
      bold: true,
      color: "FFFFFF",
      align: "center",
      shrinkText: true,
    });
    slide.addText("Questions?", {
      x: 1,
      y: 4,
      w: 8,
      h: 0.6,
      fontSize: 28,
      color: "FFFFFF",
      align: "center",
      shrinkText: true,
    });
    slide.addText("Generated by AI PPT Chat", {
      x: 1,
      y: 6.5,
      w: 8,
      h: 0.4,
      fontSize: 14,
      color: "FFFFFF",
      align: "center",
    });
  }

  return await pptx.write("blob");
}

export function buildPptxWithTheme(structure, theme = "purple") {
  return buildPptxFromJson(structure, theme);
}